import Head from "next/head";
import Content from "../components/Content";
import Layout from "../components/Layout";
import Portfolio from "../components/Portfolio";

export default function Home() {
    return (
        <Layout>
            <Head>
                <title>윤군이 포트폴리오</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Content />
            <Portfolio />
        </Layout>
    );
}
